### PR TITLE
Revert to data generator when no data received

### PR DESCRIPTION
**Pull request by rjmcneill**
Relates to #464

### CODE REVIEW

**Comment by rjmcneill** [comment]
Worth merging #478 first.
Also, probably worth sorting out the problem with the websocket triggering a render before the historic data is fetched (don't think we have an issue number for it atm)

**Comment by djmiley** [comment]
Looks good.

**Comment by rjmcneill** [comment]
Todo: 

Finish rebase

**Comment by djmiley** [comment]
Is this blocked anymore? @rjmcneill

**Comment by rjmcneill** [comment]
Don't think so @djmiley 
I'll look at getting it up to date next week :smile:

**Comment by rjmcneill** [comment]
This has been redone with the recent changes in mind.
The error notification is also now added.

If anyone wants to test it, I found the easiest way was to set the periods of the  BTC-EUR to include 1 second.
This should cause a fallover to data gen.

If anyone needs a hand with that, let me know!

**Pull request closed without merging**
