### PR TITLE
Selectors repositioned to head on mobile.

### LINKED ISSUE #403: Re-position menus

### PR DESCRIPTION
**Pull request by jdhodges**
Closes #403.

### CODE REVIEW

**Comment by rjmcneill** [comment]
LGTM @jdhodges431 

One issue with it though is how squashed everything looks on mobile.
I think it's probably because of our addition of the product dropdown in the mobile designs that UX didn't have.  So I guess that's sort of blocked by them until we know what they want.
Screenshot shows this.
Also, the clear all button is pushed out into the margin now I think.

mobileview

**Comment by jdhodges431** [comment]
Yeah may be able to make the buttons smaller, the spec doesn't give a size.

**Comment by jleft** [comment]
I agree with @rjmcneill - it does look fairly squashed and losing the clear all button isn't ideal.

I'll ask for confirmation on how a product should be selected on mobile. For now, I'd suggest, that we replace the product selectors dropdown text with an icon on mobile, if that seems reasonable?

product-search

There's also quite a lot of padding in the Add Indicator button either side of the text - is this something which can be reduced? (At least on mobile.)

**Comment by jdhodges431** [comment]
Sorry for wasting everyone's precious time with that first attempt. Hopefully this should be an improvement :pray:

**Pull request merged**
